### ISSUE TITLE
can't create percona_pmm resource

### ISSUE THREAD

**Issue by vadimtk** [Percona-Lab/terraform-provider-percona#3]
│ Error: create instances: Security group sg-0090e7124678ac474 and subnet subnet-0717327991f2d84d3 belong to different networks.
│ 
│   with percona_pmm.pmm3,
│   on main.tf line 11, in resource "percona_pmm" "pmm3":
│   11: resource "percona_pmm" "pmm3" {

**Comment by pooknull** [comment]
Fixed in 9e52ec99e93fa7065d93b4f834f1ad9f9d2ec72b
